/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ulp.lab1_tp5;

/**
 *
 * @author andrew
 */
public class Directorio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Directorio.class.getName());

    /**
     * Creates new form Directorio
     */
    public Directorio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMClientes = new javax.swing.JMenu();
        jMIAgregar = new javax.swing.JMenuItem();
        jMIBuscar = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMDirectorio = new javax.swing.JMenu();
        jMIBuscarPorCiudad = new javax.swing.JMenuItem();
        jMIBuscarPorApellido = new javax.swing.JMenuItem();
        jMCiudades = new javax.swing.JMenu();
        jMIAgregarCiudad = new javax.swing.JMenuItem();
        jMSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );

        jMClientes.setText("Clientes");

        jMIAgregar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMIAgregar.setText("Agregar Cliente");
        jMIAgregar.addActionListener(this::jMIAgregarActionPerformed);
        jMClientes.add(jMIAgregar);

        jMIBuscar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMIBuscar.setText("Buscar Cliente");
        jMIBuscar.addActionListener(this::jMIBuscarActionPerformed);
        jMClientes.add(jMIBuscar);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setText("Borrar Cliente");
        jMClientes.add(jMenuItem1);

        jMenuBar1.add(jMClientes);

        jMDirectorio.setText("Directorio");

        jMIBuscarPorCiudad.setText("Buscar Clientes por Ciudad");
        jMDirectorio.add(jMIBuscarPorCiudad);

        jMIBuscarPorApellido.setText("Buscar Clientes por Apellido");
        jMDirectorio.add(jMIBuscarPorApellido);

        jMenuBar1.add(jMDirectorio);

        jMCiudades.setText("Ciudades");

        jMIAgregarCiudad.setText("Agregar Ciudad");
        jMIAgregarCiudad.addActionListener(this::jMIAgregarCiudadActionPerformed);
        jMCiudades.add(jMIAgregarCiudad);

        jMenuBar1.add(jMCiudades);

        jMSalir.setText("Salir");
        jMenuBar1.add(jMSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMIAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMIAgregarActionPerformed

    private void jMIBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMIBuscarActionPerformed

    private void jMIAgregarCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIAgregarCiudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMIAgregarCiudadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Directorio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMCiudades;
    private javax.swing.JMenu jMClientes;
    private javax.swing.JMenu jMDirectorio;
    private javax.swing.JMenuItem jMIAgregar;
    private javax.swing.JMenuItem jMIAgregarCiudad;
    private javax.swing.JMenuItem jMIBuscar;
    private javax.swing.JMenuItem jMIBuscarPorApellido;
    private javax.swing.JMenuItem jMIBuscarPorCiudad;
    private javax.swing.JMenu jMSalir;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
